services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:dev-ubuntu24.04
    volumes:
      - ..:/workspace
      - ${HOME:-/home/qiudeng}/.ssh:/home/ubuntu/.ssh
    env_file:
      - ./.env
    command: sleep 365d

  rabbitmq:
    image: m.daocloud.io/docker.io/library/rabbitmq:management
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: qiudeng
      RABBITMQ_DEFAULT_PASS: qiudeng
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit loopback_users []
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5