services:
  devcontainer:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
    volumes:
      - ..:/workspace
      - ${HOME:-/home/qiudeng}/.ssh:/home/ubuntu/.ssh
    env_file:
      - ./.env
    user: ubuntu

  redis:
    image: m.daocloud.io/docker.io/library/redis