services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:dev-22-bookworm
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - redis

  redis:
    image: m.daocloud.io/docker.io/library/redis
    restart: unless-stopped